name: Trinh Phan 
description: Persional website of Trinh Phan
url: http://phancanhtrinh.github.io

markdown: kramdown
permalink: /:categories/:title/
repository: phancanhtrinh/phancanhtrinh.github.io    

title : TrinhPHAN
tagline: Molecular basis of fungal virulence and drug resistance
institution:
  url: https://www.maxperutzlabs.ac.at/
  name: Medical University of Vienna
department:
  url: https://www.maxperutzlabs.ac.at/
  name: Medical Biochemistry
author :
  name : TrinhPHAN
  email : phancanht99@univie.ac.at
  github : phancanhtrinh
  twitter : phancanhtrinh

future: true
sass:
  sass_dir: css

plugins: ['jekyll-twitter-plugin']

open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)
# Google Analytics
google_analytics: G-HRMVH10FQZ

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/nextflu/auspice/index.html"
  - "projects/nextflu/auspice/css/*"
  - "projects/nextflu/auspice/h3n2/*"
  - "projects/nextflu/auspice/h1n1pdm/*"
  - "projects/nextflu/auspice/vic/*"
  - "projects/nextflu/auspice/yam/*"
  - "projects/nextflu/auspice/zika/*"
  - "projects/nextflu/auspice/zibra/*"
  - "projects/nextflu/auspice/muttree/*"
  - "projects/nextflu/auspice/reports/*"
  - "projects/nextflu/auspice/js/*"
  - "projects/nextflu/auspice/cdc/*"
  - "projects/nextflu/auspice/gisaid/*"
  - "projects/auspice/src/*"
  - "projects/siv-cst/beast/main/empiricalTrees/xml/*"
  - "projects/siv-cst/beast/supplement/discreteTraits/xml/*"
  - "projects/siv-cst/beast/supplement/empiricalTrees/xml/*"
  - "projects/h3n2-reassortment/auspice/*"
  - "projects/dengue-antigenic-dynamics/titer_model/seasia_output/*"
  - "projects/h5n1-cambodia/data/tree-jsons/*"
  - "projects/zika-colombia/supplemental-analysis/rarefaction-curves/*"
